import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:talent_pitch/app/models/category.dart';

/// Associates our `categories_response.dart` with the code generated by Freezed
part 'categories_response.freezed.dart';

/// Since our CategoriesResponse class is serializable, we must add this line.
part 'categories_response.g.dart';

@freezed
class CategoriesResponse with _$CategoriesResponse {
  const factory CategoriesResponse({
    required List<Category> data,
  }) = _CategoriesResponse;

  factory CategoriesResponse.fromJson(Map<String, Object?> json) =>
      _$CategoriesResponseFromJson(json);
}
