import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:talent_pitch/app/models/talent.dart';

/// Associates our `talents_response.dart` with the code generated by Freezed
part 'talents_response.freezed.dart';

/// Since our TalentsResponse class is serializable, we must add this line.
part 'talents_response.g.dart';

@freezed
class TalentsResponse with _$TalentsResponse {
  const factory TalentsResponse({
    required List<Talent> data,
  }) = _TalentsResponse;

  factory TalentsResponse.fromJson(Map<String, Object?> json) =>
      _$TalentsResponseFromJson(json);
}
