import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:talent_pitch/app/enums/category.dart';
import 'package:talent_pitch/app/models/base_model.dart';
import 'package:talent_pitch/app/models/transformers/nullable_empty_string.dart';

/// Associates our `category.dart` with the code generated by Freezed
part 'category.freezed.dart';

/// Since our Category class is serializable, we must add this line.
part 'category.g.dart';

@freezed
class Category with _$Category {
  const factory Category({
    required String key,
    required CategoryType type,
    required String title,
    required String url,
    @JsonKey(fromJson: nullableEmptyString) String? image,
    @Default([])
    @JsonKey(
        name: 'loaded_models',
        defaultValue: [],
        includeFromJson: false,
        required: false)
    List<BaseModel> models,
  }) = _Category;

  factory Category.fromJson(Map<String, Object?> json) =>
      _$CategoryFromJson(json);
}
