import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:talent_pitch/app/models/transformers/nullable_empty_string.dart';

/// Associates our `challenge.dart` with the code generated by Freezed
part 'challenge.freezed.dart';

/// Since our Challenge class is serializable, we must add this line.
part 'challenge.g.dart';

@freezed
class Challenge with _$Challenge {
  const factory Challenge({
    required int id,
    required String name,
    required String description,
    @JsonKey(name: 'company_name')
    required String companyName,
    @JsonKey(fromJson: nullableEmptyString)
    String? video,
    @JsonKey(fromJson: nullableEmptyString)
    String? image,
  }) = _Challenge;

  factory Challenge.fromJson(Map<String, Object?> json) =>
      _$ChallengeFromJson(json);
}
