import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:talent_pitch/app/models/transformers/nullable_empty_string.dart';

/// Associates our `company.dart` with the code generated by Freezed
part 'company.freezed.dart';

/// Since our Company class is serializable, we must add this line.
part 'company.g.dart';

@freezed
class Company with _$Company {
  const factory Company({
    required int id,
    required String name,
    required String description,
    required String city,
    @JsonKey(fromJson: nullableEmptyString)
    String? video,
    @JsonKey(fromJson: nullableEmptyString)
    String? logo,
  }) = _Company;

  factory Company.fromJson(Map<String, Object?> json) =>
      _$CompanyFromJson(json);
}
