import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:talent_pitch/app/models/transformers/nullable_empty_string.dart';

/// Associates our `talent.dart` with the code generated by Freezed
part 'talent.freezed.dart';

/// Since our Talent class is serializable, we must add this line.
part 'talent.g.dart';

@freezed
class Talent with _$Talent {
  const factory Talent({
    required int id,
    required String name,
    required String email,
    @JsonKey(name: 'want_to_be', fromJson: nullableEmptyString)
    String? wantToBe,
    @JsonKey(fromJson: nullableEmptyString)
    String? avatar,
    @JsonKey(fromJson: nullableEmptyString)
    String? about,
  }) = _Talent;

  factory Talent.fromJson(Map<String, Object?> json) =>
      _$TalentFromJson(json);
}
